sudo: required
dist: trusty
language: python

matrix:
    include:
        - python: 3.6
          env: CC=clang CXX=clang++

# command to install dependencies
install:
    - pip install coverage coveralls
    - python setup.py install;
 
# command to run tests
script: 
    - nosetests --verbosity=2
