package:
  name: piqs
  version: "1.1"

source:
  git_rev: v0.1.1
  git_url: https://github.com/nathanshammah/piqs.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
  run:
    - python
    - numpy
    - cython
    - scipy
    - qutip

about:
  home: https://github.com/nathanshammah/piqs
  license: BSD
  license_file: LICENSE
